version: 2
jobs:
  lint_js:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
      - run:
          command: |
            set -eux -o pipefail
            pushd web
            yarn
            yarn lint
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
          paths:
            - "web/node_modules"

workflows:
  version: 2
  all:
    jobs:
      - lint_js
